baseURL = 'https://jordenkreps.com/'
languageCode = 'en-us'
title = 'jordenkreps dot com'
theme = 'PaperMod'

[params]
name = 'jorden kreps'
disableThemeToggle = true

[params.label]
text = 'jordenkreps dot com'

[[menus.main]]
name = 'home'
url = '/'
weight = 1

[[menus.main]]
name = 'resume'
url = '/resume/'
weight = 2

[markup.goldmark.renderer]
unsafe = true
